language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
    - node_modules
on:
  branch: master
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci
